### PR TITLE
Enhance mapping by adding custom metadata

### PR DESCRIPTION
**Pull request by jecuendet**

### CODE REVIEW

**Comment by mkopylec** [comment]
I don't really think it is necessary.
Could you please provide some example use cases for the `metadata`?
If there are some, maybe their configuration can be defined explicitly, not by `Map`.

**Comment by mkopylec** [comment]
OK, you're right.
Workarounds can't be done without additional mappings configuration.
Please change the destination branch of #54 to pull-requests.

**Comment by jecuendet** [comment]
Done. Switched to pull-request branch

**Comment by jecuendet** [comment]
Would you create a 2.4.1?

**Pull request merged**
